### ISSUE TITLE
Display message if user input 0 for turnip price or quantity

### ISSUE THREAD

**Issue by Coteh** [Coteh/ac-turnip-calculator#7]
I'm thinking this message can appear when the user clicks off the input box.

if 0 turnip price
"Please enter a price"

if 0 turnip quantity
"Please enter a turnip quantity"

**Comment by Xaconi** [comment]
Hey @Coteh , can I work on this one?

**Comment by Coteh** [comment]
I was just about to say go for it but you already did it lol

**Comment by Xaconi** [comment]
@Coteh Hey, can you add the "hacktoberfest" topic to the Repository to mark this Repository as valid for the Hacktoberfect?

**Comment by Coteh** [comment]
Oh yeah thanks for pointing that out. I just read the update from Digital Ocean and added the "hacktoberfest" topic. :)
